from .views_imports import *
from .views_saisie_marchandise import *
from .views_saisie_rfa import *
from .views_saisie_redevances import *
from .views_saisie_publicites import *
from .views_saisie_formations import *
from .views_saisie_personnels import *
from .views_saisie_materiels import *
from .views_saisie_prestations import *
from .views_saisie_abonnements import *
from .views_saisie_divers import *
