from .view_big_category_change import *
from .views_cct_change import *
from .views_etape_2_1 import *
from .views_etape_2_1_A import *
from .views_etape_2_1_B import *
from .views_etape_2_2 import *
from .views_etape_3_1 import *
from .views_etape_3_1_A import *
from .views_etape_3_2 import *
from .views_etape_3_3 import *
from .views_etape_3_5 import *
from .views_etape_3_6 import *
from .views_etape_5_0 import *
from .views_etape_5_0A import *
from .views_etape_5_0B import *
from .views_etape_5_1 import *
from .views_etape_5_3 import *
from .views_etape_5_3A import *
from .views_etape_5_5 import *
from .views_etape_rfa import *
from .views_without_third_party_num import *
